version: '3'
services:
  database:
      image: 'mongo'
      container_name: 'mongo-ah'
      environment:
          - MONGO_INITDB_DATABASE=animal-house-db
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=secret
      volumes:
          - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
          - ./database-data:/data/db
      ports:
          - '27017-27019:27017-27019'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@database:27017/
