version: '3'
services:
  database:
      image: 'mongo'
      container_name: 'mongo-ah'
      environment:
          - MONGO_INITDB_DATABASE=animal-house-db
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=secret
      volumes:
          - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
          - ./mongo-volume:/data/db
      ports:
          - '27017-27019:27017-27019'
  swagger:
    image: 'swaggerapi/swagger-editor'
    ports:
          - '8081:8080'

