swagger: "2.0"
info:
  description: Animal houz back&.
  version: 1.0.0
  title: Swagger Petstore
host: localhost:8080
basePath: /v1
tags:
- name: pet
- name: store
- name: users
- name: community
- name: market
    
schemes:
- http
paths:
  /users/register:
    post:
      tags:
      - users
      summary: Create new user
      parameters:
      - in: body
        name: body
        description: UserCreation
        required: true
        schema:
          type: object
          properties:
              username:
                type: string
              password:
                type: string
              email:
                type: string
              firstName:
                type: string
              lastName:
                type: string
      responses:
        200:
          description: Success
  /users/login:
    post:
      tags:
      - users
      summary: Login as an user
      parameters:
      - in: body
        name: body
        description: login
        required: true
        schema:
          type: object
          properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Success  
          schema:
            type: object
            properties:
              token:
                type: string
  /users/:
    get:
      tags:
      - users
      summary: Get all users
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/User"
            
  /users/current:
    get:
      tags:
      - users
      summary: Retrieve information about the current users
      security:  
        - JWT: []
      responses:
        200:
          description: ok
          schema:
            type: object
            properties:
              usersname:
                type: string
              _id:
                type: string
                
  /users/{id}:
    get:
      tags:
      - users
      summary: Get a user by ID
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Numeric ID of the user to get
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            $ref: "#/definitions/User"
  
  /users/{id}/score:
    get:
      tags:
      - users
      summary: Get game scores of the specified user
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Guid of the user
        - in: query
          name: gameId
          type: string
          required: false
          description: Optional id of the game you want the result
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              type: object
              properties:
                  gameGuid:
                    type: string
                  score:
                    type: number
    put:
      tags:
      - users
      summary: Add a game score to the specified user
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Guid of the user
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
                gameId:
                  type: string
                score:
                  type: number
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            type: object
            properties:
                gameGuid:
                  type: string
                score:
                  type: number
  /users/{id}/cart:
    get:
      tags:
      - users
      summary: Get the cart of the specified user
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Id of the user
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/ProductInstance"
    put:
      tags:
      - users
      summary: Add a product to the cart of the specified user
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Id of the user
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/ProductInstance"  
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/ProductInstance" 
    delete:
      tags:
      - users
      summary: Delete a product from the cart of the specified user
      description: Takes in the body a list of string representing the product instance ids you want to delete
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: Id of the user
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              type:
                string 
      security:
      - JWT: []
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/ProductInstance"
  /pet:
    get:
        tags:
        - pet
        summary: Finds Pet
        operationId: getPet
        parameters:
        - name: id
          in: query
          description: Id of the pet
          required: true
          type: integer
        responses:
          200:
            description: successful operation
            schema: 
              $ref: "#/definitions/Pet"
    post:
      tags:
      - pet
      summary: Add a new pet
      operationId: addPet
      parameters:
      - in: body
        name: body
        description: Pet object
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        200:
          description: Success
          
  /community/game/:
    get:
        tags:
        - community
        summary: Finds all games
        responses:
          200:
            description: successful operation
            schema: 
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  _id:
                    type: string
  /community/game/scoreboard:
    get:
        tags:
        - community
        summary: Finds the results for the scoreboard
        parameters:
          - in: query
            name: gameId
            type: string
            required: false
            description: Optional id of the game you want the results
        responses:
          200:
            description: successful operation
            schema: 
              type: array
              items:
                type: object
                properties:
                  gameId:
                    type: string
                  gameName:
                    type: string
                  scores:
                    type: array
                    items:
                      type: object
                      properties:
                        username:
                          type: string
                        userId:
                          type: string
                        score:
                          type: array
                          items:
                            type: number
  
  /market/products/:
    get:
        tags:
        - market
        summary: Finds all products
        responses:
          200:
            description: successful operation
            schema: 
              type: array
              items:
                $ref: "#/definitions/Product"

  /market/products/{id}:
    get:
        tags:
        - market
        summary: Searches the specified product
        parameters:
          - in: path
            name: id
            type: string
            required: true
            description: Id of the product to be searched
        responses:
          200:
            description: successful operation
            schema: 
              type: array
              items:
                $ref: "#/definitions/Product"
    delete:
      tags:
      - market
      summary: Deletes a product based on the received id
      parameters: 
        - in: path
          name: id
          type: string
          required: true
          description: Id of the product to be deleted
      responses:
        200:
          description: successful operation

  /market/products:
    post:
        tags:
        - market
        summary: Creates a new product
        parameters:
          - in: body
            name: body
            description: UserCreation
            required: true
            schema:
              type: object
              properties:
                  username:
                    type: string
                  password:
                    type: string
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
        responses:
          200:
            description: Success


                
                
            
securityDefinitions:  
  JWT:  
    type: apiKey  
    in: header  
    name: authorization 
    
    
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phone:
        type: string
      pets:
        type: array # todo
        items:
          type: object
          properties:
            id:
              type: integer
            name: 
              type: string
      address: 
        type: object
        properties:
          country:
            type: string
          city:
            type: string
          street:
            type: string
          cap:
            type: integer
      
      
  Species:
    type: string
    enum: &SPECIES
      - Dog
      - Cat
      - Duck
      - Fox
      - Koala
      - Panda
      - Rabbit
      
  Pet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      ownerId:
        type: integer
      specie:
        type: string
        enum: *SPECIES
      age:
        type: integer
  
  Product:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      description:
        type: string
      price:
        type: number
      categoryId:
        type: string
      image:
        type: string
      animalTargets:
        type: array
        items:
          type: string
      colors:
        type: array
        items:
          type: string
      sizes:
        type: array
        items:
          type: string
      details:
        type: string

  ProductInstance:
    type: object
    required:
      - productId
    properties:
      productId:
        type: string
      color:
        type: string
      size:
        type: string
      type:
        type: string
    
  Shop:
    type: object
    properties:
      id:
        type: integer
        format: int64
      address: 
        type: object
        properties:
          country:
            type: string
          city:
            type: string
          street:
            type: string
          cap:
            type: integer
      products:
        type: array
        items:
          type: object
          properties:
            productId:
              type: integer
            quantity:
              type: integer
